/**
 * `voidspace:shot` — a storyboard panel as a FIRST-CLASS block.
 *
 * WHY THIS EXISTS, AND WHAT IT REPLACES
 * A shot used to be an `affine:frame` with loose canvas blocks sitting inside
 * it, kept in order by an "arranger" that repositioned them after every change.
 * That model generated an entire class of defect and never stopped:
 *
 *   • a block you can drag is a block that can be cloned, stranded, or fought
 *     over by the arranger mid-gesture;
 *   • membership was geometric, so a picture one pixel out was silently not in
 *     the shot;
 *   • "scrollable" had to be faked with paging, because a canvas has no
 *     scrollable sub-region;
 *   • sizing was only uniform if the arranger happened to run.
 *
 * A shot OWNS its media as data. There is no free block to duplicate, nothing to
 * arrange, and the lanes are ordinary DOM rows that scroll because DOM rows
 * scroll. The whole category is gone rather than patched.
 *
 * WHY A CUSTOM BLOCK IS THE RIGHT CALL HERE
 * The standing rule in this codebase is "use BlockSuite's own primitive" — and
 * it has been right every time it was applied. It does not apply here: BlockSuite
 * has no primitive for a storyboard panel with typed media slots and scrolling
 * reference lanes. `BlockViewExtension` + a `GfxBlockComponent` is the SUPPORTED
 * way to add one, so this is using the extension API rather than working around
 * it. Nothing is forked.
 *
 * WHAT THE AGENT SEES
 * Everything, in one read. `board_read` returns these props verbatim — title,
 * the three written fields, and every reference with its role and url. No
 * containment scan, no geometry, no second structure to keep in step.
 */
import { GfxCompatible, type GfxCommonBlockProps } from '@blocksuite/std/gfx';
import { BlockModel, BlockSchemaExtension, defineBlockSchema } from '@blocksuite/store';

/**
 * What a piece of media is FOR.
 *
 * Explicit, never inferred: a still in a shot might be the frame the video
 * should START on, the frame it should END on, a clip whose camera move should
 * be copied, or just a reference. Nothing about it says which, and a wrong
 * first-frame silently produces the wrong video.
 */
export type NamedMediaRole =
  | 'reference' | 'firstFrame' | 'lastFrame' | 'motionRef' | 'sfx' | 'bgm'
  // ── Composition roles. A graphic shot is not generated by a video model, so
  // its media are LAYOUT positions rather than model inputs. Same vocabulary
  // `compose_scene` already takes, so nothing is translated on the way out.
  | 'background' | 'figure' | 'inset' | 'logo' | 'texture';

/**
 * A graphic may ALSO use its block's own slot keys as roles.
 *
 * `browser-mockup` wants a `screenshot`, `photo-quote-split` wants a `portrait`.
 * Making the slot key BE the role is what lets one set of machinery serve both
 * kinds of shot — exclusivity, the inspector's dropdown, drop-on-a-well and
 * compile all work unchanged. `rolesFor` is what says which are legal here.
 */
export type MediaRole = NamedMediaRole | (string & {});



export const MEDIA_ROLES: readonly MediaRole[] = [
  'reference', 'firstFrame', 'lastFrame', 'motionRef', 'sfx', 'bgm',
  'background', 'figure', 'inset', 'logo', 'texture',
] as const;

export const ROLE_LABEL: Record<MediaRole, string> = {
  reference: 'Reference',
  firstFrame: 'First frame',
  lastFrame: 'Last frame',
  motionRef: 'Motion ref',
  sfx: 'Sound effect',
  bgm: 'Music',
  background: 'Background',
  figure: 'Figure',
  inset: 'Inset',
  logo: 'Logo',
  texture: 'Texture',
};

/**
 * A human label for a role, INCLUDING a block's own slot key.
 *
 * `ROLE_LABEL` only knows the fixed vocabulary, so a graphic using its block's
 * slots — `screenshot`, `portrait`, `bg-video` — indexed to `undefined` and
 * rendered the literal word "undefined" in the dropdown and on the tile.
 * Anything unknown is humanised from the key itself, which is what the block's
 * author named it and therefore the best label available.
 */
export function roleLabel(role: MediaRole): string {
  const known = (ROLE_LABEL as Record<string, string | undefined>)[role];
  if (known) return known;
  return String(role)
    .replace(/[-_]+/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/^\w/, c => c.toUpperCase());
}

/**
 * WHAT KIND OF SHOT THIS IS, and it decides the vocabulary of everything inside.
 *
 *   clip        — generated by a video model from references and prompts.
 *   hyperframes — a motion-graphic COMPOSITION, rendered from a designed block
 *                 rather than generated. A kinetic title, a stat card, a list.
 *
 * TWO, NOT THREE. The studio's scene kinds are `avatar | video | hyperframes`,
 * where `avatar` differs from `video` only in auto-attaching the presenter's
 * likeness. That distinction does not belong on the board: here the user (or
 * the agent, on their behalf) attaches the references they actually want, so a
 * shot that should carry a face carries a face — explicitly, visibly, and
 * without a hidden rule deciding it. Compile emits `video` for every clip,
 * which is precisely the kind that adds nothing on its own.
 *
 * A hyperframes shot is a genuinely different object: no first frame, no motion
 * reference, no video model. Offering those would be offering settings that do
 * nothing. What it has instead is a BLOCK with declared slots, and a layout
 * with places to put media — and those places are `COMPOSITION_REF_ROLES`
 * verbatim (`composables/studio/hyperframesScenes.ts`), so the board and the
 * renderer are naming the same things.
 */
export type ShotKind = 'clip' | 'hyperframes';

export const SHOT_KINDS: readonly ShotKind[] = ['clip', 'hyperframes'] as const;

export const SHOT_KIND_LABEL: Record<ShotKind, string> = {
  clip: 'Video clip',
  hyperframes: 'Graphic',
};

export const SHOT_KIND_HINT: Record<ShotKind, string> = {
  clip: 'Generated by a video model from the references you attach',
  hyperframes: 'A HyperFrames block — title, stat, list. Rendered, not generated.',
};

/**
 * Accept what the studio's own resolver accepts.
 *
 * `resolveSceneKind` (pinned by `composables/studio/sceneKind.test.ts`) reads
 * `graphic`/`explainer` as hyperframes and `broll`/`narrative` as video,
 * because those are the words an agent reaches for. Reading the same aliases
 * here means a board written by an agent that said "graphic" is not silently
 * the wrong kind of scene.
 */
export function normaliseShotKind(raw: unknown): ShotKind {
  const k = String(raw || 'clip').toLowerCase();
  return (k === 'hyperframes' || k === 'graphic' || k === 'explainer') ? 'hyperframes' : 'clip';
}

/**
 * The roles a piece of media may legitimately hold, given the shot it is in and
 * what the media IS.
 *
 * ONE FUNCTION, because the alternative is three lists that drift: the tile's
 * click-cycle, the inspector's dropdown, and whatever the agent is told. A
 * still cannot be a motion reference (there is no motion in it) and a clip
 * cannot be a first frame (a frame is one image) — offering either is offering
 * a setting that silently does nothing downstream.
 */
export function rolesFor(
  shotKind: ShotKind,
  mediaKind: ShotMedia['kind'],
  /**
   * The chosen block's media slots, when this is a graphic.
   *
   * THE BLOCK DECIDES, not a fixed vocabulary. `browser-mockup` wants a
   * `screenshot`; `photo-quote-split` wants a `portrait`. Offering every
   * graphic the same background/figure/logo trio was offering most of them
   * three controls that do nothing and hiding the one that matters. Callers
   * that have not resolved a block yet pass nothing and get the generic set,
   * which is also what the 26 baked-in blocks legitimately use.
   */
  blockSlots?: Array<{ key: string; kind: string }>,
): MediaRole[] {
  if (mediaKind === 'audio') return ['sfx', 'bgm', 'reference'];
  if (shotKind === 'hyperframes') {
    const declared = (blockSlots ?? [])
      .filter(sl => (mediaKind === 'video'
        // A slot that wants a still can still hold a clip's poster frame, so a
        // video is offered both; a slot that wants footage cannot take a still.
        ? sl.kind === 'video' || sl.kind === 'image'
        : sl.kind === 'image'))
      .map(sl => sl.key as MediaRole);
    // `reference` is always last and always available: it is where media that
    // is not filling a slot lives, and every shot needs somewhere to park a
    // mood board still.
    if (declared.length) return [...declared, 'reference'];

    // No declared slots — the generic composition roles, filtered by medium.
    return mediaKind === 'video'
      ? ['background', 'inset', 'texture', 'reference']
      : ['background', 'figure', 'inset', 'logo', 'texture', 'reference'];
  }
  return mediaKind === 'video'
    // A clip has motion to copy but is not a single frame.
    ? ['reference', 'motionRef']
    // A still can be the frame it opens or ends on, but has no motion to copy.
    : ['reference', 'firstFrame', 'lastFrame'];
}

/** True when the role is one the given shot/media combination can actually hold. */
export function roleIsLegal(
  shotKind: ShotKind,
  mediaKind: ShotMedia['kind'],
  role: MediaRole,
  blockSlots?: Array<{ key: string; kind: string }>,
): boolean {
  return rolesFor(shotKind, mediaKind, blockSlots).includes(role);
}

/**
 * WHAT A REFERENCE IS OF — a different question from what it is FOR.
 *
 * `role` says how the model consumes it (the frame it opens on, a plain
 * reference, the score). `refKind` says what the thing IS, and that is what
 * makes a reference addressable in a prompt.
 *
 * This exists because of how Seedance-class models actually work. References
 * arrive as positional tags — `@Image1`, `@Image2`, `@Video1` — and the prompt
 * refers back to them by NUMBER. A prompt that says "@Image2 walks into frame"
 * is unreadable to a human and impossible for the agent to write reliably three
 * turns later. With a kind and a name, the same reference is "@Image2 (Sarah,
 * character)", the legend compile emits says so, and both the user and the agent
 * can talk about "Sarah" while the model still receives its number.
 *
 * Deliberately a SHORT list. Every entry here has to mean something different to
 * a generation model; "mood" and "vibe" would be two words for `style`.
 */
export type RefKind =
  /** A person or creature whose identity must persist across shots. */
  | 'character'
  /** Look: palette, grade, film stock, rendering style. */
  | 'style'
  /** Where it happens — set, room, landscape. */
  | 'location'
  /** A thing that must appear exactly right: a product, a logo, a prop. */
  | 'product'
  /** What someone is wearing, kept separate from who they are. */
  | 'wardrobe';

/**
 * `action` USED TO BE HERE AND WAS REMOVED.
 *
 * It said "a movement to copy" — which is what the `motionRef` ROLE already
 * says, and says better: the role decides how the model consumes the thing,
 * and no reference is ever a movement-to-copy without being a motion
 * reference. Two fields answering one question is two chances to disagree, and
 * a dropdown offering a choice that changes nothing is worse than one option
 * fewer.
 */
export const REF_KINDS: readonly RefKind[] = [
  'character', 'style', 'location', 'product', 'wardrobe',
] as const;

export const REF_KIND_LABEL: Record<RefKind, string> = {
  character: 'Character',
  style: 'Style',
  location: 'Location',
  product: 'Product',
  wardrobe: 'Wardrobe',
};

/**
 * Normalise a reference name into something a prompt can carry.
 *
 * Lowercase, no spaces, no punctuation: the tag is written into a generation
 * prompt beside an `@Image2`, and a name with a space in it splits into two
 * tokens where the second one means nothing.
 */
export function normaliseTag(raw: string): string {
  return raw.trim().toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 32);
}

/** One reference on a shot. Plain JSON so the agent reads it without decoding. */
export interface ShotMedia {
  /** Stable within the shot; what the agent addresses to change or remove it. */
  id: string;
  kind: 'image' | 'video' | 'audio';
  role: MediaRole;
  /** What this reference is OF. See `RefKind`. */
  refKind?: RefKind;
  /**
   * The name it goes by — "sarah", "the-kitchen", "hero-mug".
   *
   * Written into the compiled reference legend next to the model's positional
   * tag, so a motion prompt can say what it means and the model still gets its
   * `@Image2`. Normalised by `normaliseTag`.
   */
  tag?: string;
  /** Where it came from, when that is not the user's own library. Web imports
   *  are recorded so provenance survives into the compiled project. */
  sourceUrl?: string;
  credit?: string;
  /**
   * What the CARD shows — a server thumbnail or a 720p proxy. Never the master:
   * a 190px tile does not need 4K, and pulling one is the slow path.
   */
  src: string;
  /** FULL QUALITY. The canvas draws `src`; the render must use this. */
  url: string;
  /** A still for a clip, so a card costs one small image and never a stream. */
  poster?: string;
  name: string;
  /** Voidspace Library id, carried into the compiled project. */
  mediaId?: string;
  scope?: string;
  /** Real byte size, known from the Library listing. Carried so a card can state
   *  what a clip weighs without anyone downloading it to find out. */
  bytes?: number;

  /**
   * HOW TO USE THIS, in the user's own words.
   *
   * "Use this sting under the intro, right as she says 'hello everybody'." That
   * sentence is a direction, and there is nowhere else for it to live: `role`
   * says what slot the thing occupies and `tag` says what it is, but neither can
   * carry intent. Without it the instruction stays in the user's head and the
   * generated video quietly ignores it.
   *
   * Free text on purpose. It is written by a person (or dictated), read by a
   * person, and passed to the planner verbatim — structuring it would mean
   * inventing a grammar for something whose whole value is that it is not one.
   */
  note?: string;

  /**
   * THE PART OF THE CLIP THAT IS ACTUALLY THE REFERENCE.
   *
   * A shot is a few seconds; a recording is minutes. Somebody who films one
   * take and storyboards from it is not attaching "the video" to scene 3 — they
   * mean the four seconds where she turns to the window. Without an in/out the
   * only options are attaching the whole take (and hoping the model picks the
   * right moment) or cutting the file up first, which defeats the point of
   * storyboarding before you edit.
   *
   * Seconds from the START of the media, `outSec` exclusive. Both undefined
   * means the whole thing — the common case, and it stays cheap.
   */
  inSec?: number;
  outSec?: number;
  /** The media's own length, once something has measured it. Needed to draw a
   *  trim bar and to clamp an out-point that would run past the end. */
  durationSec?: number;
}

/** Does a trim window mean anything for this kind? Stills have no time axis. */
export function isTimed(kind: ShotMedia['kind']): boolean {
  return kind === 'video' || kind === 'audio';
}

/** `72.4` → `1:12.4`. Short form, because a trim readout is glanced at. */
export function formatTime(sec: number): string {
  if (!Number.isFinite(sec) || sec < 0) return '0:00';
  const m = Math.floor(sec / 60);
  const s = sec - m * 60;
  return `${m}:${s < 10 ? '0' : ''}${s.toFixed(1)}`;
}

/**
 * The window a reference actually plays, given what is set.
 *
 * One function so the inspector, the tile and compile cannot disagree about
 * what "trimmed" means — and so an out-point left past the end of a clip is
 * clamped in exactly one place.
 */
export function trimWindow(m: ShotMedia): { start: number; end: number; trimmed: boolean } {
  const dur = m.durationSec && m.durationSec > 0 ? m.durationSec : 0;
  const start = Math.max(0, m.inSec ?? 0);
  const rawEnd = m.outSec ?? dur;
  const end = dur > 0 ? Math.min(dur, rawEnd || dur) : rawEnd;
  const trimmed = start > 0.01 || (dur > 0 && end < dur - 0.01);
  return { start, end: end > start ? end : (dur || start), trimmed };
}

/** Which lane a medium belongs to. Kind decides it, so nothing can be misfiled. */
export function laneOf(kind: ShotMedia['kind']): 'image' | 'video' | 'audio' {
  return kind;
}

/**
 * Roles that are ONE PER SHOT — a named slot rather than a lane.
 *
 * Two consequences, both of which is why this list has to be complete:
 *  • Setting one DEMOTES whatever held it (see `setMediaRole`). A shot with two
 *    first frames, or a composition with two backgrounds, is a contradiction
 *    the render would have to guess about.
 *  • Dropping ONTO the slot assigns the role (see `handleAssetDrop`). A role
 *    missing here means the card draws a labelled drop well that accepts the
 *    file and then quietly files it as a generic reference — which is exactly
 *    what a graphic's BACKGROUND / FIGURE / LOGO wells did until these five
 *    were added.
 */
export const SLOT_ROLES = [
  'firstFrame', 'lastFrame', 'motionRef',
  // The composition holes. A block has one of each.
  'background', 'figure', 'inset', 'logo', 'texture',
] as const;
export type SlotRole = (typeof SLOT_ROLES)[number];

export function isSlotRole(role: MediaRole): role is SlotRole {
  return (SLOT_ROLES as readonly string[]).includes(role);
}

/**
 * The written fields.
 *
 * Plain strings, not rich text. Every one is consumed by the video pipeline —
 * `action` becomes the scene description in `spec.screenplay`, `voiceover` the
 * spoken line, `camera` the framing the motion prompt is built from — so the
 * agent should be able to read and write them without parsing a Y.Text.
 */
export interface ShotFields {
  action: string;
  voiceover: string;
  camera: string;
}

export const FIELD_SPECS: ReadonlyArray<{
  key: keyof ShotFields; label: string; placeholder: string;
}> = [
  { key: 'action', label: 'ACTION', placeholder: 'What happens in this shot' },
  { key: 'voiceover', label: 'VOICEOVER', placeholder: 'The line that gets spoken' },
  { key: 'camera', label: 'CAMERA', placeholder: 'Framing, movement, how long' },
] as const;

type ShotProps = {
  title: string;
  action: string;
  voiceover: string;
  camera: string;
  media: ShotMedia[];
  /**
   * The video model this shot will be generated with, as a registry id.
   *
   * PER SHOT, not per board, because shots genuinely differ: the one with a
   * spoken line needs a model with native dialogue, the one that has to end on
   * an exact frame needs `supportsLastFrame`, and the establishing wide can go
   * to the cheapest tier. Choosing once for a whole video means every shot pays
   * for the most demanding one.
   *
   * Empty means "not chosen yet" — the project's default is used, and the agent
   * should be asking. It is never guessed silently here: a model decides what
   * references are even legal, so an unnoticed default is a shot built from the
   * wrong inputs.
   */
  model: string;
  /** Planned length in seconds. Clamped to the model's allowed values at
   *  generation time; kept here because the pacing is a story decision. */
  durationSec: number;
  /** `clip` (generated) or `hyperframes` (a composition). See `ShotKind`. */
  kind: ShotKind;
  /**
   * The designed block a graphic shot is built from — the `name` in its
   * `block.json`, which is what `find_blocks` reports and `compose_scene`
   * takes. Empty means "not chosen yet": a graphic waiting on a decision
   * rather than a broken one.
   *
   * BY NAME, not by copying the HTML. Blocks are created, shared and reused —
   * a user's own block shadows a starter of the same name, and the library
   * grows underneath a board that was made months ago. Storing the name means
   * the shot follows the block; storing a snapshot would freeze it and quietly
   * diverge from the one the user is still editing.
   */
  composition: string;
  /**
   * Values for the block's declared slots and variables — exactly what
   * `compose_scene { block, variables }` takes.
   *
   * A block declares `slots` (a CSS selector, a kind and a sample) and/or
   * `variables` (bare names). This is the map of key → the words THIS shot
   * puts in them. Kept on the shot rather than derived from the written fields
   * because a block's slots are its own vocabulary: `stat` and `caption` on a
   * stat-card are not the same thing as ACTION and VOICEOVER, and guessing a
   * mapping between them is how a card ends up saying the wrong number.
   */
  compositionVars: Record<string, string>;
} & GfxCommonBlockProps;

/** Panel geometry. Width is fixed; height is whatever the content needs, and the
 *  component keeps `xywh` in step so canvas selection matches what is drawn. */
export const SHOT_W = 640;
export const SHOT_H = 720;
export const SHOT_GAP = 56;

export const ShotBlockSchema = defineBlockSchema({
  flavour: 'voidspace:shot',
  props: (): ShotProps => ({
    title: '',
    action: '',
    voiceover: '',
    camera: '',
    media: [],
    model: '',
    durationSec: 0,
    kind: 'clip',
    composition: '',
    compositionVars: {},
    xywh: `[0,0,${SHOT_W},${SHOT_H}]`,
    index: 'a0',
    lockedBySelf: false,
    scale: 1,
    rotate: 0,
  }),
  metadata: {
    version: 1,
    role: 'content',
    // On the SURFACE, like every other canvas object. Not the page: a shot is a
    // thing on a board, not a section of a document.
    parent: ['affine:surface'],
    children: [],
  },
  toModel: () => new ShotBlockModel(),
});

export class ShotBlockModel extends GfxCompatible<ShotProps>(BlockModel) {}

export const ShotBlockSchemaExtension = BlockSchemaExtension(ShotBlockSchema);
