/**
 * `voidspace:shot` — a storyboard panel as a FIRST-CLASS block.
 *
 * WHY THIS EXISTS, AND WHAT IT REPLACES
 * A shot used to be an `affine:frame` with loose canvas blocks sitting inside
 * it, kept in order by an "arranger" that repositioned them after every change.
 * That model generated an entire class of defect and never stopped:
 *
 *   • a block you can drag is a block that can be cloned, stranded, or fought
 *     over by the arranger mid-gesture;
 *   • membership was geometric, so a picture one pixel out was silently not in
 *     the shot;
 *   • "scrollable" had to be faked with paging, because a canvas has no
 *     scrollable sub-region;
 *   • sizing was only uniform if the arranger happened to run.
 *
 * A shot OWNS its media as data. There is no free block to duplicate, nothing to
 * arrange, and the lanes are ordinary DOM rows that scroll because DOM rows
 * scroll. The whole category is gone rather than patched.
 *
 * WHY A CUSTOM BLOCK IS THE RIGHT CALL HERE
 * The standing rule in this codebase is "use BlockSuite's own primitive" — and
 * it has been right every time it was applied. It does not apply here: BlockSuite
 * has no primitive for a storyboard panel with typed media slots and scrolling
 * reference lanes. `BlockViewExtension` + a `GfxBlockComponent` is the SUPPORTED
 * way to add one, so this is using the extension API rather than working around
 * it. Nothing is forked.
 *
 * WHAT THE AGENT SEES
 * Everything, in one read. `board_read` returns these props verbatim — title,
 * the three written fields, and every reference with its role and url. No
 * containment scan, no geometry, no second structure to keep in step.
 */
import { GfxCompatible, type GfxCommonBlockProps } from '@blocksuite/std/gfx';
import { BlockModel, BlockSchemaExtension, defineBlockSchema } from '@blocksuite/store';

/**
 * What a piece of media is FOR.
 *
 * Explicit, never inferred: a still in a shot might be the frame the video
 * should START on, the frame it should END on, a clip whose camera move should
 * be copied, or just a reference. Nothing about it says which, and a wrong
 * first-frame silently produces the wrong video.
 */
export type NamedMediaRole =
  | 'reference' | 'firstFrame' | 'lastFrame' | 'motionRef' | 'sfx' | 'bgm'
  // ── Composition roles. A graphic shot is not generated by a video model, so
  // its media are LAYOUT positions rather than model inputs. Same vocabulary
  // `compose_scene` already takes, so nothing is translated on the way out.
  | 'background' | 'figure' | 'inset' | 'logo' | 'texture';

/**
 * A graphic may ALSO use its block's own slot keys as roles.
 *
 * `browser-mockup` wants a `screenshot`, `photo-quote-split` wants a `portrait`.
 * Making the slot key BE the role is what lets one set of machinery serve both
 * kinds of shot — exclusivity, the inspector's dropdown, drop-on-a-well and
 * compile all work unchanged. `rolesFor` is what says which are legal here.
 */
export type MediaRole = NamedMediaRole | (string & {});



export const MEDIA_ROLES: readonly MediaRole[] = [
  'reference', 'firstFrame', 'lastFrame', 'motionRef', 'sfx', 'bgm',
  'background', 'figure', 'inset', 'logo', 'texture',
] as const;

export const ROLE_LABEL: Record<MediaRole, string> = {
  reference: 'Reference',
  firstFrame: 'First frame',
  lastFrame: 'Last frame',
  motionRef: 'Motion ref',
  sfx: 'Sound effect',
  bgm: 'Music',
  background: 'Background',
  figure: 'Figure',
  inset: 'Inset',
  logo: 'Logo',
  texture: 'Texture',
};

/**
 * A human label for a role, INCLUDING a block's own slot key.
 *
 * `ROLE_LABEL` only knows the fixed vocabulary, so a graphic using its block's
 * slots — `screenshot`, `portrait`, `bg-video` — indexed to `undefined` and
 * rendered the literal word "undefined" in the dropdown and on the tile.
 * Anything unknown is humanised from the key itself, which is what the block's
 * author named it and therefore the best label available.
 */
export function roleLabel(role: MediaRole): string {
  const known = (ROLE_LABEL as Record<string, string | undefined>)[role];
  if (known) return known;
  return String(role)
    .replace(/[-_]+/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/^\w/, c => c.toUpperCase());
}

/**
 * WHAT KIND OF SHOT THIS IS, and it decides the vocabulary of everything inside.
 *
 *   clip        — generated by a video model from references and prompts.
 *   hyperframes — a motion-graphic COMPOSITION, rendered from a designed block
 *                 rather than generated. A kinetic title, a stat card, a list.
 *
 * TWO, NOT THREE. The studio's scene kinds are `avatar | video | hyperframes`,
 * where `avatar` differs from `video` only in auto-attaching the presenter's
 * likeness. That distinction does not belong on the board: here the user (or
 * the agent, on their behalf) attaches the references they actually want, so a
 * shot that should carry a face carries a face — explicitly, visibly, and
 * without a hidden rule deciding it. Compile emits `video` for every clip,
 * which is precisely the kind that adds nothing on its own.
 *
 * A hyperframes shot is a genuinely different object: no first frame, no motion
 * reference, no video model. Offering those would be offering settings that do
 * nothing. What it has instead is a BLOCK with declared slots, and a layout
 * with places to put media — and those places are `COMPOSITION_REF_ROLES`
 * verbatim (`composables/studio/hyperframesScenes.ts`), so the board and the
 * renderer are naming the same things.
 */
export type ShotKind = 'clip' | 'hyperframes';

export const SHOT_KINDS: readonly ShotKind[] = ['clip', 'hyperframes'] as const;

export const SHOT_KIND_LABEL: Record<ShotKind, string> = {
  clip: 'Video clip',
  hyperframes: 'Graphic',
};

export const SHOT_KIND_HINT: Record<ShotKind, string> = {
  clip: 'Generated by a video model from the references you attach',
  hyperframes: 'A HyperFrames block — title, stat, list. Rendered, not generated.',
};

/**
 * Accept what the studio's own resolver accepts.
 *
 * `resolveSceneKind` (pinned by `composables/studio/sceneKind.test.ts`) reads
 * `graphic`/`explainer` as hyperframes and `broll`/`narrative` as video,
 * because those are the words an agent reaches for. Reading the same aliases
 * here means a board written by an agent that said "graphic" is not silently
 * the wrong kind of scene.
 */
export function normaliseShotKind(raw: unknown): ShotKind {
  const k = String(raw || 'clip').toLowerCase();
  return (k === 'hyperframes' || k === 'graphic' || k === 'explainer') ? 'hyperframes' : 'clip';
}

/**
 * The roles a piece of media may legitimately hold, given the shot it is in and
 * what the media IS.
 *
 * ONE FUNCTION, because the alternative is three lists that drift: the tile's
 * click-cycle, the inspector's dropdown, and whatever the agent is told. A
 * still cannot be a motion reference (there is no motion in it) and a clip
 * cannot be a first frame (a frame is one image) — offering either is offering
 * a setting that silently does nothing downstream.
 */
export function rolesFor(
  shotKind: ShotKind,
  mediaKind: ShotMedia['kind'],
  /**
   * The chosen block's media slots, when this is a graphic.
   *
   * THE BLOCK DECIDES, not a fixed vocabulary. `browser-mockup` wants a
   * `screenshot`; `photo-quote-split` wants a `portrait`. Offering every
   * graphic the same background/figure/logo trio was offering most of them
   * three controls that do nothing and hiding the one that matters. Callers
   * that have not resolved a block yet pass nothing and get the generic set,
   * which is also what the 26 baked-in blocks legitimately use.
   */
  blockSlots?: Array<{ key: string; kind: string }>,
): MediaRole[] {
  if (mediaKind === 'audio') return ['sfx', 'bgm', 'reference'];
  if (shotKind === 'hyperframes') {
    const declared = (blockSlots ?? [])
      .filter(sl => (mediaKind === 'video'
        // A slot that wants a still can still hold a clip's poster frame, so a
        // video is offered both; a slot that wants footage cannot take a still.
        ? sl.kind === 'video' || sl.kind === 'image'
        : sl.kind === 'image'))
      .map(sl => sl.key as MediaRole);
    // `reference` is always last and always available: it is where media that
    // is not filling a slot lives, and every shot needs somewhere to park a
    // mood board still.
    if (declared.length) return [...declared, 'reference'];

    // No declared slots — the generic composition roles, filtered by medium.
    return mediaKind === 'video'
      ? ['background', 'inset', 'texture', 'reference']
      : ['background', 'figure', 'inset', 'logo', 'texture', 'reference'];
  }
  return mediaKind === 'video'
    // A clip has motion to copy but is not a single frame.
    ? ['reference', 'motionRef']
    // A still can be the frame it opens or ends on, but has no motion to copy.
    : ['reference', 'firstFrame', 'lastFrame'];
}

/** True when the role is one the given shot/media combination can actually hold. */
export function roleIsLegal(
  shotKind: ShotKind,
  mediaKind: ShotMedia['kind'],
  role: MediaRole,
  blockSlots?: Array<{ key: string; kind: string }>,
): boolean {
  return rolesFor(shotKind, mediaKind, blockSlots).includes(role);
}

/**
 * WHAT A REFERENCE IS OF — a different question from what it is FOR.
 *
 * `role` says how the model consumes it (the frame it opens on, a plain
 * reference, the score). `refKind` says what the thing IS, and that is what
 * makes a reference addressable in a prompt.
 *
 * This exists because of how Seedance-class models actually work. References
 * arrive as positional tags — `@Image1`, `@Image2`, `@Video1` — and the prompt
 * refers back to them by NUMBER. A prompt that says "@Image2 walks into frame"
 * is unreadable to a human and impossible for the agent to write reliably three
 * turns later. With a kind and a name, the same reference is "@Image2 (Sarah,
 * character)", the legend compile emits says so, and both the user and the agent
 * can talk about "Sarah" while the model still receives its number.
 *
 * Deliberately a SHORT list. Every entry here has to mean something different to
 * a generation model; "mood" and "vibe" would be two words for `style`.
 */
export type RefKind =
  /** A person or creature whose identity must persist across shots. */
  | 'character'
  /** Look: palette, grade, film stock, rendering style. */
  | 'style'
  /** Where it happens — set, room, landscape. */
  | 'location'
  /** A thing that must appear exactly right: a product, a logo, a prop. */
  | 'product'
  /** What someone is wearing, kept separate from who they are. */
  | 'wardrobe';

/**
 * `action` USED TO BE HERE AND WAS REMOVED.
 *
 * It said "a movement to copy" — which is what the `motionRef` ROLE already
 * says, and says better: the role decides how the model consumes the thing,
 * and no reference is ever a movement-to-copy without being a motion
 * reference. Two fields answering one question is two chances to disagree, and
 * a dropdown offering a choice that changes nothing is worse than one option
 * fewer.
 */
export const REF_KINDS: readonly RefKind[] = [
  'character', 'style', 'location', 'product', 'wardrobe',
] as const;

export const REF_KIND_LABEL: Record<RefKind, string> = {
  character: 'Character',
  style: 'Style',
  location: 'Location',
  product: 'Product',
  wardrobe: 'Wardrobe',
};

/**
 * Normalise a reference name into something a prompt can carry.
 *
 * Lowercase, no spaces, no punctuation: the tag is written into a generation
 * prompt beside an `@Image2`, and a name with a space in it splits into two
 * tokens where the second one means nothing.
 */
export function normaliseTag(raw: string): string {
  return raw.trim().toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 32);
}

/** One reference on a shot. Plain JSON so the agent reads it without decoding. */
export interface ShotMedia {
  /** Stable within the shot; what the agent addresses to change or remove it. */
  id: string;
  kind: 'image' | 'video' | 'audio';
  role: MediaRole;
  /** What this reference is OF. See `RefKind`. */
  refKind?: RefKind;
  /**
   * The name it goes by — "sarah", "the-kitchen", "hero-mug".
   *
   * Written into the compiled reference legend next to the model's positional
   * tag, so a motion prompt can say what it means and the model still gets its
   * `@Image2`. Normalised by `normaliseTag`.
   */
  tag?: string;
  /** Where it came from, when that is not the user's own library. Web imports
   *  are recorded so provenance survives into the compiled project. */
  sourceUrl?: string;
  credit?: string;
  /**
   * What the CARD shows — a server thumbnail or a 720p proxy. Never the master:
   * a 190px tile does not need 4K, and pulling one is the slow path.
   */
  src: string;
  /** FULL QUALITY. The canvas draws `src`; the render must use this. */
  url: string;
  /** A still for a clip, so a card costs one small image and never a stream. */
  poster?: string;
  name: string;
  /** Voidspace Library id, carried into the compiled project. */
  mediaId?: string;
  scope?: string;
  /** Real byte size, known from the Library listing. Carried so a card can state
   *  what a clip weighs without anyone downloading it to find out. */
  bytes?: number;

  /**
   * HOW TO USE THIS, in the user's own words.
   *
   * "Use this sting under the intro, right as she says 'hello everybody'." That
   * sentence is a direction, and there is nowhere else for it to live: `role`
   * says what slot the thing occupies and `tag` says what it is, but neither can
   * carry intent. Without it the instruction stays in the user's head and the
   * generated video quietly ignores it.
   *
   * Free text on purpose. It is written by a person (or dictated), read by a
   * person, and passed to the planner verbatim — structuring it would mean
   * inventing a grammar for something whose whole value is that it is not one.
   */
  note?: string;

  /**
   * THE PART OF THE CLIP THAT IS ACTUALLY THE REFERENCE.
   *
   * A shot is a few seconds; a recording is minutes. Somebody who films one
   * take and storyboards from it is not attaching "the video" to scene 3 — they
   * mean the four seconds where she turns to the window. Without an in/out the
   * only options are attaching the whole take (and hoping the model picks the
   * right moment) or cutting the file up first, which defeats the point of
   * storyboarding before you edit.
   *
   * Seconds from the START of the media, `outSec` exclusive. Both undefined
   * means the whole thing — the common case, and it stays cheap.
   */
  inSec?: number;
  outSec?: number;
  /** The media's own length, once something has measured it. Needed to draw a
   *  trim bar and to clamp an out-point that would run past the end. */
  durationSec?: number;
}

/** Does a trim window mean anything for this kind? Stills have no time axis. */
export function isTimed(kind: ShotMedia['kind']): boolean {
  return kind === 'video' || kind === 'audio';
}

/**
 * WHERE A TAKE CAME FROM.
 *
 * A take is anything this shot PRODUCED, not only a model output. A recording,
 * an upload, a file dragged in from somewhere else — if it is an attempt at
 * this shot, it is a take, and it should sit beside the generated ones and be
 * choosable in the same way.
 *
 * Modelling it any other way means a second mechanism for "the footage I shot
 * myself", and then two things that both mean "this is the shot" — which is the
 * drift this whole design exists to avoid.
 */
export type TakeSource = 'generated' | 'recorded' | 'uploaded' | 'imported';

/**
 * ONE ATTEMPT AT THIS SHOT.
 *
 * ── TAKES ARE OUTPUTS; `media` ARE INPUTS ────────────────────────────────────
 * They are a separate list rather than a `ShotMedia` with a `take` role, and the
 * separation is the point: references are what the shot is MADE FROM and takes
 * are what it BECAME. Folding them together would make every existing consumer
 * of `media` — the lanes, the wells, `rolesFor`, compile's reference legend —
 * filter takes back out, and the first one that forgot would put the finished
 * clip into the model's own reference set.
 *
 * ── APPEND-ONLY, AND THAT IS A PRODUCT DECISION ──────────────────────────────
 * Generating never replaces. It adds. So trying again is free, an agent cannot
 * destroy work somebody paid for, and "the one before was better" is always
 * recoverable. `chosenTakeId` is the only thing that ever changes.
 */
export interface ShotTake {
  /** Stable within the shot. What the agent, the card and the timeline address. */
  id: string;

  /**
   * Voidspace Library id — and THE FILE BELONGS TO THE LIBRARY, not to this
   * block.
   *
   * Load-bearing: a take may already be cut into the film when its shot is
   * deleted. Because the timeline clip references Library media rather than
   * this block, deleting the shot can never break the cut. Absent only while a
   * generation is still running.
   */
  mediaId?: string;

  /** What the CARD draws — a poster or 720p proxy. Never the master: a tile is
   *  a hundred pixels and pulling a 4K file for one is the slow path. */
  src: string;
  /** FULL QUALITY. The card draws `src`; the render must use this. The recurring
   *  silent bug in this codebase is these two being swapped. */
  url: string;
  /** A still, so a take tile costs one small image and never a stream. */
  poster?: string;

  /** A clip shot yields video; a graphic yields its render. Decides which track
   *  the take lands on when the film is assembled. */
  kind: 'video' | 'image';
  /** Real length, measured. What the shot's slot on the timeline becomes. */
  durationSec: number;

  /**
   * `running` is a REAL, PERSISTED state, not a UI flag.
   *
   * A generation outlives the tab it was started in. Storing the state (and
   * `jobId` below) is what lets a reload show "still working" and resume
   * polling, instead of showing a shot that quietly lost the thing it was
   * making — which is indistinguishable from never having started.
   */
  status: 'running' | 'ready' | 'failed';
  /** Why it failed, in words a person can read. */
  error?: string;
  /**
   * The provider/job handle to resume polling after a reload.
   *
   * THE REAL HANDLE, not a local correlation id. This field existed from the
   * start and was being filled with the board's own progress-toast id
   * (`shot_<timestamp>`), which no machine has ever heard of — so the resume it
   * was added for could not be written, and a take whose tab closed mid-render
   * stayed `running` forever. Nothing read it, so nothing complained.
   */
  jobId?: string;
  /**
   * WHICH MACHINE owns `jobId`, for a local render.
   *
   * A job id only means something on the node that ran it: asking loopback about
   * a job on the workstation reports "no such job" and would abandon a render
   * that is going perfectly well. Absent for cloud takes, which are addressed by
   * provider task id alone.
   */
  nodeVia?: 'loopback' | 'mesh';
  nodeName?: string;

  /** ISO 8601. Orders the strip, and answers "is there a newer take than the
   *  one on the timeline?". */
  createdAt: string;
  /** The user's own name for it — "the good one". */
  label?: string;

  source: TakeSource;
  /** Registry id of the model that made it. Shown on the tile, and what "same
   *  again" reuses. Absent for anything not generated. */
  model?: string;
  /** Which surface ran it. `local` is what tells the user this one was free. */
  runtime?: 'local' | 'cloud';
  /** Reproducibility. "Same, but at night, same seed" is the core iteration
   *  loop for anyone on their own hardware. */
  seed?: number;
  /** What ACTUALLY went to the model, after the prompt was composed. Provenance
   *  the card cannot otherwise reconstruct three edits later. */
  promptUsed?: string;
  /** What it cost, as charged. */
  costCredits?: number;
}

/** Takes worth putting on a timeline: finished, and with something to play. */
export function readyTakes(takes: readonly ShotTake[] | undefined): ShotTake[] {
  return (takes ?? []).filter(t => t.status === 'ready' && (t.url || t.src));
}

/**
 * The take that IS the shot.
 *
 * Falls back to the newest ready take when nothing is chosen, so a shot that
 * generated once and was never explicitly ticked still has an answer — the
 * common case, and asking the user to confirm the only candidate would be
 * ceremony. Returns null when there is genuinely nothing to show.
 */
export function chosenTake(
  takes: readonly ShotTake[] | undefined,
  chosenTakeId: string | undefined,
): ShotTake | null {
  const ready = readyTakes(takes);
  if (!ready.length) return null;
  const picked = chosenTakeId ? ready.find(t => t.id === chosenTakeId) : undefined;
  if (picked) return picked;
  return ready.reduce((newest, t) => (t.createdAt > newest.createdAt ? t : newest), ready[0]);
}

/**
 * A take, described the way everything else on the board is described.
 *
 * The viewer, the drag payload and the asset panel all speak ONE language —
 * `ShotMedia` — so a take is translated once, here, rather than every consumer
 * learning a second shape. Lives in the model and not in the viewer because the
 * card, the drag and the dialog all need it, and the card must not import the
 * chrome (the chrome already imports the card's document, and the cycle would
 * take the editor down at boot rather than at the call).
 *
 * `id` stays the TAKE'S id. It is what `chooseTake` and `removeTake` address,
 * and it is deliberately NOT a media id — see the note on `AssetDragEntity`.
 */
export function takeAsMedia(t: ShotTake): ShotMedia {
  return {
    id: t.id,
    kind: t.kind === 'image' ? 'image' : 'video',
    // A take is not a reference to anything; the role exists because every
    // `ShotMedia` has one, and nothing reads it off a take.
    role: 'reference',
    // `src` is what a PLAYER should stream and `url` is full quality. Takes
    // store them the same way round, and the recurring silent bug in this
    // codebase is swapping them — hence one place that does it.
    src: t.src || t.url,
    url: t.url || t.src,
    ...(t.poster ? { poster: t.poster } : {}),
    name: t.label || 'Take',
    ...(t.mediaId ? { mediaId: t.mediaId } : {}),
    ...(t.durationSec ? { durationSec: t.durationSec } : {}),
  };
}

/**
 * The picture a take tile may draw, or '' for none.
 *
 * ── THE RULE, AND THE DOWNLOAD IT PREVENTS ───────────────────────────────────
 * The card drew `t.poster || t.src`, and on a video take `src` is THE CLIP. So
 * every take that had not been given a still handed an .mp4 to an `<img>`: the
 * browser fetched the whole file, failed to decode it, and drew nothing. Nine
 * takes on one card was nine video downloads for nine blank tiles, and a board
 * of fifty shots was a stall with no visible cause — the requests are for files
 * the page is not playing, so nothing on screen suggests why.
 *
 * `src` is a legitimate thumbnail in exactly one case, which is when the take IS
 * a picture. `kind` is what says so, and it is the only thing that does.
 */
export function takeThumb(t: Pick<ShotTake, 'poster' | 'src' | 'kind'>): string {
  return t.poster || (t.kind === 'image' ? t.src : '') || '';
}

/**
 * A GRAPHIC THAT RUNS OVER THE SHOT, rather than instead of it.
 *
 * ── WHY THIS IS A LIST AND NOT A SECOND `kind` ───────────────────────────────
 * `kind` answers "what fills the frame" — footage, or a full-frame composition.
 * That is a real question and it stays. What it could never answer is "and a
 * lower third over the top", because a shot was allowed exactly one of the two
 * and a graphic consumed the whole slot.
 *
 * Layers make the third case ordinary: a clip with two overlays, a graphic bed
 * with a ticker over it, or no layers at all — which is every shot that exists
 * today, unchanged.
 *
 * ── AND WHY THE BED IS NOT ONE OF THEM ───────────────────────────────────────
 * A `hyperframes` shot keeps `composition` / `compositionVars`. Folding the bed
 * into `graphics[0]` would have been tidier on paper and would have rewritten
 * every board on disk to gain nothing: `slots.ts`, `checkShot`, the card's block
 * picker and compile all already speak that pair. The layers sit ON TOP of
 * whatever the shot's picture turns out to be, which is exactly what makes them
 * work identically over footage and over a bed.
 *
 * ── EVERY FIELD HERE IS ABOUT SURVIVING THE EDITOR ───────────────────────────
 * A graphic is anchored to the shot's SLOT, never to a take. Takes come and go,
 * get re-chosen, and measure different lengths; a layer that pinned itself to
 * one of them would be on the wrong picture the moment somebody auditioned an
 * alternate. `offsetSec` + `anchor` are how it stays put.
 */
export interface ShotGraphic {
  /** Stable within the shot. What the card, the agent and the timeline address. */
  id: string;
  /**
   * The block name, resolved against the installed library the same way
   * `ShotProps.composition` is. Empty means "chosen a layer, not a block yet" —
   * a state the card shows as a picker rather than as an error.
   */
  block: string;
  /**
   * Key → value for the block's own declared slots: media urls, typed words and
   * colours together, exactly what `slotFills` produces and what the render
   * route's `slots` takes.
   *
   * ONE MAP, not three. A block's slots are one vocabulary — `screenshot`,
   * `headline`, `accent` — and splitting them by kind here would mean every
   * consumer re-joining them against `block.json` to do anything useful.
   */
  slots: Record<string, string>;
  /**
   * HOW THIS GRAPHIC MEETS THE PICTURE. The user's choice, per layer.
   *
   *   overlay — rendered TRANSPARENT and laid over the shot on its own track.
   *             The picture underneath is still a separate clip: retime the
   *             graphic, trim it, delete it, swap the take beneath it, all
   *             without re-rendering anything. Costs a render of the GRAPHIC'S
   *             length, so a 3s lower third is 3 seconds of work whether the
   *             shot under it runs 8 seconds or ten minutes.
   *
   *   bake    — the shot's picture is composited INTO the render and the result
   *             is one flat clip. This is the only way a block can HOLD the
   *             footage rather than sit on it — a browser frame with a screen
   *             recording in its window, a phone mockup, a masked reveal — and
   *             it is the only way to get a single self-contained file.
   *
   * ── WHY THIS IS A CHOICE AND NOT A RULE ──────────────────────────────────
   * An earlier design derived it from the block's own `overlay` flag. That is a
   * good default and a bad law: the flag says what the DESIGNER intended, and
   * plenty of legitimate work goes against it — burning a lower third in on
   * purpose because the clip is going somewhere that cannot carry two tracks,
   * or laying a "full-frame" block over footage because it happens to be mostly
   * transparent. The flag still picks the default; the user picks the answer.
   *
   * ── WHAT BAKING COSTS, SAID PLAINLY ──────────────────────────────────────
   * It is bound to ONE take and it is not retimable. Change the words, pick a
   * different take, or move the graphic half a second, and the whole clip is
   * re-rendered — at a cost that scales with the FOOTAGE, not the graphic. That
   * is why `overlay` is the default.
   */
  mode: 'overlay' | 'bake';
  /** Seconds from the shot's start (or its end — see `anchor`). */
  offsetSec: number;
  /** How long it stays up. 0 means "to the end of the shot". */
  durationSec: number;
  /**
   * WHICH END OF THE SHOT IT HOLDS ONTO, and this exists because takes measure
   * different lengths.
   *
   * Choose an 8s take over a 5s one and the shot's slot grows by three seconds.
   * A lower third introducing the speaker belongs at the top and should not
   * move (`start`). An end card belongs on the last beat and must follow the
   * new ending (`end`). Neither is a sensible default for the other, and
   * guessing is how a graphic lands over black.
   */
  anchor: 'start' | 'end';
  /**
   * The rendered alpha clip, once it exists. Written by compile, never by hand.
   *
   * Empty is the normal state of a layer that has just been added — the card
   * shows the block's own preview until a render replaces it.
   */
  renderedUrl?: string;
  /** Library id of that render, so deleting the shot cannot break a cut that
   *  already uses it. Same rule as a take's `mediaId`, for the same reason. */
  mediaId?: string;
  /** Measured length of `renderedUrl`. The clip's slot on the timeline. */
  renderedDurationSec?: number;
  /**
   * WHAT WAS RENDERED, hashed — and this is what makes recompiling cheap.
   *
   * A render is a function of the block, its values, the length and the aspect.
   * Storing the hash of those means a second compile can prove the existing file
   * is still correct and skip the work; change one word and exactly one layer
   * re-renders. Without it every compile re-renders every graphic, and a board
   * with nine of them becomes something people avoid pressing.
   */
  renderHash?: string;
  /** Why the last render failed, in words a person can read. Cleared on success. */
  error?: string;
}

/** A layer worth compositing: it names a block, and it has a file to show. */
export function readyGraphics(gs: readonly ShotGraphic[] | undefined): ShotGraphic[] {
  return (gs ?? []).filter(g => g.block && g.renderedUrl);
}

/** True for a layer the user has asked to burn into the picture. */
export function isBaked(g: Pick<ShotGraphic, 'mode'>): boolean {
  return g.mode === 'bake';
}

/**
 * A LAYER ALWAYS STARTS AS AN OVERLAY, and this is deliberately NOT derived from
 * the block.
 *
 * An earlier draft read the block's own `overlay` flag and started a
 * non-overlay block as a bake. It looked clever and it was wrong twice:
 *
 *  1. `overlay: false` is the ABSENCE of a claim at least as often as it is a
 *     claim. Nothing forces a block author to set it, and a block with no
 *     manifest opinion normalises to false — so "the designer says this is
 *     full-frame" and "nobody said anything" were the same value, and both
 *     silently chose the destructive mode.
 *  2. A bake needs a take to bake ONTO. On a storyboard most shots have not been
 *     generated when the graphic is added, so that default lands the user with a
 *     layer that refuses to render until they go and do something else first.
 *
 * So the default is the reversible one, always. The block's flag earns its keep
 * as a WARNING instead — `checkGraphic` says when an overlay is built from a
 * block that paints its own background, which is the case the flag actually
 * predicts.
 */
export function defaultGraphicMode(): 'overlay' | 'bake' {
  return 'overlay';
}

/**
 * What is wrong with this layer, in words the person who set it can act on.
 *
 * Same shape and same reasoning as `checkShot`: a warning the user has to go
 * looking for is a warning they will not see, so the card says it in place.
 */
export function checkGraphic(
  g: Pick<ShotGraphic, 'block' | 'mode'>,
  block: { overlay?: boolean; slots?: ReadonlyArray<{ kind: string }> } | null | undefined,
  hasPicture: boolean,
): string[] {
  const out: string[] = [];
  if (!g.block) return out;
  if (g.mode === 'bake' && !hasPicture) {
    out.push(
      'Baking needs a picture to bake onto — generate this shot, or switch back to Over.',
    );
  }
  /**
   * BAKING A BLOCK THAT PAINTS ITS OWN GROUND AND HAS NOWHERE TO PUT FOOTAGE.
   *
   * A bake puts the picture in the block's video slot when it declares one. With
   * no such slot the picture goes BEHIND the composition — and 13 of the
   * installed starters fill `#root` with an opaque colour, which covers it
   * completely. The render succeeds and the footage is simply not in it, which
   * is the worst shape a failure can take.
   */
  if (g.mode === 'bake' && block && block.overlay === false
      && !(block.slots ?? []).some(sl => sl.kind === 'video')) {
    out.push(
      `${g.block} paints its own background and has no video slot, so baking would hide `
      + 'the shot behind it. Use a block with a video slot, or leave this Over.',
    );
  }
  if (g.mode !== 'bake' && block && block.overlay === false) {
    // The single most likely way a layer disappoints: it renders correctly and
    // hides the shot, because the block was drawn to own the whole frame.
    out.push(
      `${g.block} was designed to fill the frame, not to sit on footage — over a shot it `
      + 'will cover the picture. Bake it in, or choose a block marked as an overlay.',
    );
  }
  return out;
}

/** `72.4` → `1:12.4`. Short form, because a trim readout is glanced at. */
export function formatTime(sec: number): string {
  if (!Number.isFinite(sec) || sec < 0) return '0:00';
  const m = Math.floor(sec / 60);
  const s = sec - m * 60;
  return `${m}:${s < 10 ? '0' : ''}${s.toFixed(1)}`;
}

/**
 * The window a reference actually plays, given what is set.
 *
 * One function so the inspector, the tile and compile cannot disagree about
 * what "trimmed" means — and so an out-point left past the end of a clip is
 * clamped in exactly one place.
 */
export function trimWindow(m: ShotMedia): { start: number; end: number; trimmed: boolean } {
  const dur = m.durationSec && m.durationSec > 0 ? m.durationSec : 0;
  const start = Math.max(0, m.inSec ?? 0);
  const rawEnd = m.outSec ?? dur;
  const end = dur > 0 ? Math.min(dur, rawEnd || dur) : rawEnd;
  const trimmed = start > 0.01 || (dur > 0 && end < dur - 0.01);
  return { start, end: end > start ? end : (dur || start), trimmed };
}

/** Which lane a medium belongs to. Kind decides it, so nothing can be misfiled. */
export function laneOf(kind: ShotMedia['kind']): 'image' | 'video' | 'audio' {
  return kind;
}

/**
 * Roles that are ONE PER SHOT — a named slot rather than a lane.
 *
 * Two consequences, both of which is why this list has to be complete:
 *  • Setting one DEMOTES whatever held it (see `setMediaRole`). A shot with two
 *    first frames, or a composition with two backgrounds, is a contradiction
 *    the render would have to guess about.
 *  • Dropping ONTO the slot assigns the role (see `handleAssetDrop`). A role
 *    missing here means the card draws a labelled drop well that accepts the
 *    file and then quietly files it as a generic reference — which is exactly
 *    what a graphic's BACKGROUND / FIGURE / LOGO wells did until these five
 *    were added.
 */
export const SLOT_ROLES = [
  'firstFrame', 'lastFrame', 'motionRef',
  // The composition holes. A block has one of each.
  'background', 'figure', 'inset', 'logo', 'texture',
] as const;
export type SlotRole = (typeof SLOT_ROLES)[number];

export function isSlotRole(role: MediaRole): role is SlotRole {
  return (SLOT_ROLES as readonly string[]).includes(role);
}

/**
 * The written fields.
 *
 * Plain strings, not rich text. Every one is consumed by the video pipeline —
 * `action` becomes the scene description in `spec.screenplay`, `voiceover` the
 * spoken line, `camera` the framing the motion prompt is built from — so the
 * agent should be able to read and write them without parsing a Y.Text.
 */
export interface ShotFields {
  action: string;
  voiceover: string;
  camera: string;
}

/**
 * TWO BOXES ON THE CARD, NOT THREE — and the third is not deleted.
 *
 * ACTION and CAMERA were separate boxes feeding the same thing: the motion
 * prompt. That is not how anybody writes a shot. A shot list says
 *
 *   "Wide — she turns to the window as the kettle screams, slow push in."
 *
 * in ONE sentence, with the framing inside it, because the framing is part of
 * the description. Split across two boxes, the second one is a question nobody
 * knows how to answer, and it sat empty on almost every shot.
 *
 * VOICEOVER IS THE ONE THAT MUST STAY SEPARATE, and this is the whole reason
 * the merge stops at two. The line reaches TTS **verbatim**. Fold it into prose
 * and something has to extract it again — and an extractor that paraphrases by
 * one word ships a video that says the wrong thing, with no error anywhere in
 * the chain. It is also the storyboard convention: panel description above,
 * dialogue below.
 *
 * `camera` KEEPS ITS PROP. Boards written before this carry text in it, and
 * deleting the field would silently drop a line of somebody's direction.
 * `renderFields` shows the box only when it already holds something, so an old
 * shot stays editable and a new one is never offered it. `screenplay.ts` already
 * emits `CAMERA:` conditionally, so an empty one costs nothing downstream.
 */
export const FIELD_SPECS: ReadonlyArray<{
  key: keyof ShotFields; label: string; placeholder: string;
}> = [
  {
    key: 'action',
    label: 'SHOT',
    placeholder:
      'The video: what happens, how it is framed, what it sounds like — “Wide, she turns to '
      + 'the window as the kettle screams, slow push in”',
  },
  /**
   * SEPARATE FROM THE SHOT, and that separation is the feature.
   *
   * Anything written in SHOT is a description of the VIDEO, and a model with
   * native dialogue speaks the lines it finds there, in the scene, on camera.
   * This is the other thing: a voice laid OVER the picture — the explainer
   * track, the infographic read, the documentary narrator.
   *
   * They are independent on purpose (see `voiceMode`): a shot may have both,
   * either, or neither. Merging them would force a choice the user has not made
   * and cannot express afterwards.
   */
  {
    key: 'voiceover',
    label: 'NARRATION',
    placeholder: 'A voice over the top, if you want one — spoken separately, added as a separate track on timeline',
  },
  {
    key: 'camera',
    label: 'CAMERA (older shot)',
    placeholder: 'Framing and movement — now written into SHOT above',
  },
] as const;

type ShotProps = {
  title: string;
  action: string;
  voiceover: string;
  camera: string;
  media: ShotMedia[];
  /**
   * The video model this shot will be generated with, as a registry id.
   *
   * PER SHOT, not per board, because shots genuinely differ: the one with a
   * spoken line needs a model with native dialogue, the one that has to end on
   * an exact frame needs `supportsLastFrame`, and the establishing wide can go
   * to the cheapest tier. Choosing once for a whole video means every shot pays
   * for the most demanding one.
   *
   * Empty means "not chosen yet" — the project's default is used, and the agent
   * should be asking. It is never guessed silently here: a model decides what
   * references are even legal, so an unnoticed default is a shot built from the
   * wrong inputs.
   */
  model: string;
  /** Planned length in seconds. Clamped to the model's allowed values at
   *  generation time; kept here because the pacing is a story decision. */
  durationSec: number;
  /**
   * Output size, e.g. `720p`. Empty means "whatever the model leads with".
   *
   * STORED PER SHOT, not per board, because it is a cost decision as much as
   * a quality one: a 30s establishing shot at 1080p costs more than the four
   * cutaways around it put together, and the whole point of choosing is being
   * able to spend it where it shows.
   *
   * Empty rather than a default, so a shot written before this existed reads
   * as "unset" and follows the model instead of claiming a size the model may
   * not even offer. `resolutionFor` resolves it.
   */
  resolution: string;
  /** Frame shape, e.g. `16:9`. Empty ⇒ the model decides. Same reasoning. */
  aspect: string;
  /**
   * Every attempt this shot has produced. See `ShotTake`.
   *
   * ⚠ READ IT AS `props.takes ?? []`, ALWAYS. Boards created before this field
   * existed have no `takes` key in their Yjs document at all — `props()` supplies
   * a default for NEW blocks only, it does not backfill old ones. Anything that
   * assumes an array here works on a board made today and returns `undefined` on
   * one made last week, which is the worst kind of bug: invisible until a real
   * user opens real work. `shots.ts` centralises the fix in `editTakes`.
   */
  takes: ShotTake[];
  /**
   * Which take IS the shot — the one that lands on the main video track.
   *
   * Empty means "not decided", and `chosenTake()` then falls back to the newest
   * ready take. It is a POINTER, never a copy: the take itself is never marked,
   * so changing your mind rewrites one string rather than editing two records
   * that could disagree.
   */
  chosenTakeId: string;
  /**
   * DOES THE VIDEO MODEL MAKE ITS OWN SOUND?
   *
   * ── WHY THIS IS THE USER'S CHOICE AND NOT A RULE ─────────────────────────
   * All four combinations are legitimate films, and nothing can pick between
   * them automatically, because the difference is intent:
   *
   *   silent   + no narration → a clean visual. B-roll, a cutaway, a title bed.
   *   silent   + narration    → an explainer. The picture illustrates and the
   *                             voice carries it. TTS, laid over.
   *   dialogue + no narration → a scene. The character speaks on camera, and a
   *                             narrator over the top would ruin it.
   *   dialogue + narration    → both, deliberately. A documentary beat where a
   *                             subject talks and a narrator frames it.
   *
   * So the shot carries the decision and the two written fields stay
   * independent: SHOT describes the video (including any dialogue spoken in
   * it), NARRATION is a separate voice over the top.
   *
   * `'silent' | 'dialogue'` are the SERVER'S OWN WORDS — `gen-clip-start` reads
   * exactly these — so nothing is translated on the way out. Renaming them for
   * the card would invent a second vocabulary for one concept, which is how two
   * ends drift apart.
   *
   * Empty means "not decided" and resolves to silent: it is what every shot
   * generated before this existed, and it is the answer that cannot surprise
   * somebody with a voice they never asked for.
   */
  voiceMode: '' | 'silent' | 'dialogue';
  /** `clip` (generated) or `hyperframes` (a composition). See `ShotKind`. */
  kind: ShotKind;
  /**
   * The designed block a graphic shot is built from — the `name` in its
   * `block.json`, which is what `find_blocks` reports and `compose_scene`
   * takes. Empty means "not chosen yet": a graphic waiting on a decision
   * rather than a broken one.
   *
   * BY NAME, not by copying the HTML. Blocks are created, shared and reused —
   * a user's own block shadows a starter of the same name, and the library
   * grows underneath a board that was made months ago. Storing the name means
   * the shot follows the block; storing a snapshot would freeze it and quietly
   * diverge from the one the user is still editing.
   */
  composition: string;
  /**
   * Values for the block's declared slots and variables — exactly what
   * `compose_scene { block, variables }` takes.
   *
   * A block declares `slots` (a CSS selector, a kind and a sample) and/or
   * `variables` (bare names). This is the map of key → the words THIS shot
   * puts in them. Kept on the shot rather than derived from the written fields
   * because a block's slots are its own vocabulary: `stat` and `caption` on a
   * stat-card are not the same thing as ACTION and VOICEOVER, and guessing a
   * mapping between them is how a card ends up saying the wrong number.
   */
  compositionVars: Record<string, string>;
  /**
   * GRAPHIC LAYERS OVER THIS SHOT'S PICTURE. See `ShotGraphic`.
   *
   * Independent of `kind`: a clip can carry them, and so can a graphic bed. An
   * empty list is every shot made before this existed.
   */
  graphics: ShotGraphic[];
  /**
   * WHICH SCENE OF THE SCREENPLAY THIS SHOT COVERS.
   *
   * The only link between the document and the filmstrip, and the reason either
   * is worth having. It lets the board say "this scene has no shots yet", lets
   * compile hand the editor a structured film instead of a flat list, and lets
   * the agent answer "what is this shot FOR" — which it cannot do from the shot
   * alone, because a shot only knows what it shows.
   *
   * A KEY, NOT A POSITION. `parseFountain` derives it from the slugline plus an
   * ordinal among identical sluglines, so inserting a scene at the top of the
   * script does not silently re-point every shot below it. Renaming a slugline
   * DOES orphan its shots — deliberately, because that surfaces as visible drift
   * the user can fix rather than as a silent re-binding.
   *
   * Empty is legal and common: someone sketching a visual idea before the scene
   * is written is working normally. Those shots show as off-script and compile
   * exactly as they always did.
   */
  sceneKey: string;
} & GfxCommonBlockProps;

/**
 * Panel geometry.
 *
 * WHY 760 AND NOT 720. A clip card holds a kind row, three slot wells at 16:9,
 * three reference lanes, the written fields and a footer. Measured against the
 * card's own CSS that is roughly 730px of content inside a 720px box — so the
 * last thing in the column, the footer with the model and the duration, was cut
 * off the bottom on every clip shot. Padding cannot fix an overflow; the box has
 * to be big enough, and the footer has to live somewhere the content cannot push
 * it (it is now a sibling of the scrolling body — see `.shot__foot`).
 *
 * UNIFORM, still. A graphic needs less and gets slack, which its REFERENCES lane
 * absorbs — that lane is already the one element allowed to take the slack. A
 * per-kind height means `shotBounds`, `relayoutShots` and the filmstrip all have
 * to know each shot's kind to lay out the strip, which is a real change and
 * belongs with the takes work rather than smuggled in beside a padding fix.
 */
export const SHOT_W = 640;
/**
 * 845, RAISED FROM 760 WHEN TAKES ARRIVED.
 *
 * The TAKES row costs about 85px — a label line plus a 62px strip plus its rule
 * and padding — and only a generated shot has one. The body scrolls, so nothing
 * is ever clipped either way; the difference is whether a shot you have just
 * generated shows its result and its writing at the same time, or makes you
 * scroll a card to see what you made.
 *
 * STILL UNIFORM, and still deliberately. A per-kind height means `shotBounds`,
 * `relayoutShots` and the filmstrip all have to know each shot's kind and its
 * take count to lay out the strip — and the height would then CHANGE under the
 * user the first time a generation landed, moving every card to its right. A
 * strip of equal cards that is occasionally roomier is a better trade than one
 * that reflows while you are working in it.
 *
 * ── 1020, RAISED FROM 845 WHEN GRAPHIC LAYERS ARRIVED ────────────────────────
 * The GRAPHICS row is on EVERY shot, and it is last in the body because a layer
 * is the last decision anybody makes about a shot. Measured on a real card at
 * 845: the section began 582px down a 734px card with ~170px of body hidden
 * below the fold — so the whole feature, including its empty state, sat off the
 * bottom edge of a box that does not advertise itself as scrollable.
 *
 * Ordering it earlier would have put a section most shots never use above the
 * shot's own inputs. A section nobody can find is not "correctly ordered", it is
 * absent — so the box grew instead. The body still scrolls, which is what keeps
 * three layers and nine references from being a problem; what this buys is that
 * the FIRST layer, and the invitation to add one, are visible without scrolling.
 */
export const SHOT_H = 1020;
export const SHOT_GAP = 56;

export const ShotBlockSchema = defineBlockSchema({
  flavour: 'voidspace:shot',
  props: (): ShotProps => ({
    title: '',
    action: '',
    voiceover: '',
    camera: '',
    media: [],
    takes: [],
    chosenTakeId: '',
    voiceMode: '',
    model: '',
    durationSec: 0,
    resolution: '',
    aspect: '',
    kind: 'clip',
    composition: '',
    compositionVars: {},
    graphics: [],
    sceneKey: '',
    xywh: `[0,0,${SHOT_W},${SHOT_H}]`,
    index: 'a0',
    lockedBySelf: false,
    scale: 1,
    rotate: 0,
  }),
  metadata: {
    version: 1,
    role: 'content',
    // On the SURFACE, like every other canvas object. Not the page: a shot is a
    // thing on a board, not a section of a document.
    parent: ['affine:surface'],
    children: [],
  },
  toModel: () => new ShotBlockModel(),
});

export class ShotBlockModel extends GfxCompatible<ShotProps>(BlockModel) {}

export const ShotBlockSchemaExtension = BlockSchemaExtension(ShotBlockSchema);
